/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Cart.gltf --transform
Author: Addison Moyer (https://sketchfab.com/Addison.Moyer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shopping-cart-3674ea1aabf9458dadd8332872509749
Title: Shopping Cart
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("../Cart-transformed.glb");
  return (
    <group {...props} dispose={null} scale={0.15} position={[0, -1, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.lambert3SG}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.lambert4SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Cart-transformed.glb");
