/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Croc.gltf --transform
Author: DEDROX (https://sketchfab.com/Raghavprasanna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crock-shopping-at-month-end-4ee5bcd0034d4c3189816717ff283f17
Title: Crock Shopping at month end
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Croc-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.35}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.31, 7.56, 0.4]} rotation={[0.25, -0.1, -0.01]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.crock_skin_dark_sandle}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.crock_skin_sandl}
            />
          </group>
          <group position={[0, 7.51, 0]} scale={1.01}>
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials.crock_pant_dark}
            />
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.Crock_badgew}
            />
          </group>
          <group
            position={[0.59, -2.13, -0.68]}
            rotation={[-1.49, 0, -1.27]}
            scale={[0.41, 1.07, 0.61]}
          >
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials.sapato2}
            />
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials.sapato1}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials.sapato3}
            />
          </group>
          <group
            position={[0.5, -2.16, 0.77]}
            rotation={[-1.64, -0.02, -1.96]}
            scale={[0.41, 1.07, 0.61]}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials.sapato2}
            />
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials.sapato1}
            />
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials.sapato3}
            />
          </group>
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.crock_hood_orng}
            position={[-0.28, 8.92, 0.75]}
            rotation={[0.25, -0.1, -0.01]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.crock_hood_orng}
            position={[-0.28, 8.92, 0.75]}
            rotation={[0.25, -0.1, -0.01]}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.crock_skin_sandl}
            position={[-0.31, 7.56, 0.4]}
            rotation={[0.25, -0.1, -0.01]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.crock_pant_dark}
            position={[-0.31, 7.56, 0.4]}
            rotation={[0.25, -0.1, -0.01]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.material_0}
            position={[0, 7.72, 0]}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.crock_hoodie}
            position={[0, 7.51, 0]}
            scale={1.01}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials.crock_hoodie}
            position={[0, 7.51, 0]}
            scale={1.01}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials.crock_hoodie}
            position={[0, 7.51, 0]}
            scale={1.01}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials.crock_pant_dark}
            position={[0.87, 3.71, -0.08]}
            rotation={[0.44, -0.02, -0.08]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials.crock_pant_dark}
            position={[0.87, 3.71, -0.08]}
            rotation={[0.44, -0.02, -0.08]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.crock_pant_dark}
            position={[0.92, 3.66, -0.11]}
            rotation={[0.51, 0, 0]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials.crock_pant_dark}
            position={[0.78, 3.16, 1.22]}
            rotation={[-0.01, -0.16, 0.48]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials.crock_pant_dark}
            position={[1.29, 3.7, -0.33]}
            rotation={[0.45, 0.01, -0.05]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials.crock_pant_dark}
            scale={0.58}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials.crock_skin_sandl}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.11}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials.crock_pant_dark}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={0.11}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials.crock_hood_orng}
            position={[-0.36, 7.52, -0.14]}
            rotation={[-0.02, -0.16, 0.02]}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials.crock_pant_dark}
            scale={0.58}
          />
          <mesh
            geometry={nodes.Object_54.geometry}
            material={materials.crock_skin_dark_sandle}
            position={[2.39, 7, 0.47]}
            rotation={[-0.64, 0.09, 0.01]}
            scale={0.02}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials.crock_skin_dark_sandle}
            position={[2.39, 6.97, 0.57]}
            rotation={[-1.72, 0.07, 0.07]}
            scale={0.02}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials.blinn4SG}
            position={[1.33, 3.64, -0.1]}
            rotation={[0.45, 0.01, -0.05]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_60.geometry}
            material={materials.Crock_bag}
            position={[0.15, -0.66, -1.7]}
            rotation={[0.11, 0.01, 0.08]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials.BaseMeshFemale}
            position={[-0.21, -0.16, -2.18]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials.crock_hood_orng}
            position={[0, 0.2, 0]}
            scale={0.1}
          />
          <mesh
            geometry={nodes.Object_66.geometry}
            material={materials.crock_hood_orng}
            position={[0, 0.02, 0]}
            scale={0.1}
          />
          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials.BaseMeshFemale}
            position={[-0.12, -0.65, -1.81]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_70.geometry}
            material={materials.BaseMeshFemale}
            position={[-0.12, -0.65, 1.22]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_72.geometry}
            material={materials.BaseMeshFemale}
            position={[-0.21, -0.16, 0.88]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_74.geometry}
            material={materials.BaseMeshFemale}
            position={[-0.25, -0.07, 0.91]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_76.geometry}
            material={materials.Crock_bag}
            position={[0.15, -0.66, -1.7]}
            rotation={[0.11, 0.01, 0.08]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_78.geometry}
            material={materials.Crock_bag}
            position={[0.15, -0.66, -1.7]}
            rotation={[0.11, 0.01, 0.08]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_80.geometry}
            material={materials.Crock_bag}
            position={[0.15, -0.66, -1.7]}
            rotation={[0.11, 0.01, 0.08]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_82.geometry}
            material={materials.Crock_bag}
            position={[0.15, -0.66, -1.7]}
            rotation={[0.11, 0.01, 0.08]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_84.geometry}
            material={materials.crock_hood_orng}
            position={[0.09, 4.23, -0.92]}
            rotation={[0.3, 0.02, -0.02]}
            scale={0.18}
          />
          <mesh
            geometry={nodes.Object_86.geometry}
            material={materials.keyshcain}
            position={[1.31, 3.37, 0.4]}
            rotation={[1.83, -0.15, -1.46]}
            scale={[0.38, 2.04, 0.38]}
          />
          <mesh
            geometry={nodes.Object_88.geometry}
            material={materials.blinn4SG}
            position={[1.33, 3.83, -0.49]}
            rotation={[0.4, 0.07, -1.67]}
            scale={0.47}
          />
          <mesh
            geometry={nodes.Object_90.geometry}
            material={materials.keyshcain}
            position={[0.12, 7.91, 1.82]}
            rotation={[1.62, 0.05, -0.39]}
            scale={0.58}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Croc-transformed.glb");
